# should cover dependencies of
#   pip install -e .[tutorials]
name: optson
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - h5py
  - ipympl
  - ipython
  - matplotlib
  - numpy
  - scikit-learn
