# should cover dependencies of
#   pip install -e .[ci]
name: optson
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - h5py
  - ipython
  - ipympl
  - matplotlib
  - scikit-learn
  - pytest=7.4.0
  - pytest-cov
  - mypy=1.10.0
  - flake8=7.0.0
  - flake8-pyproject
  - black=24.4.2
  - jupyter
  - jupytext
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-toolbox
  - docutils=0.18.1
  - make
  - pip
  - pip:
      - myst_nb
      - sphinx_book_theme
