FROM mambaorg/micromamba:latest
ARG MAMBA_DOCKERFILE_ACTIVATE=1
COPY --chown=$MAMBA_USER:$MAMBA_USER conda-env.yml /tmp/env.yml
RUN micromamba install --yes --file /tmp/env.yml && \
    micromamba clean --all --yes
